# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import sender_pb2 as sender__pb2


class SenderStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Send = channel.unary_unary(
        '/Sender/Send',
        request_serializer=sender__pb2.Message.SerializeToString,
        response_deserializer=sender__pb2.Message.FromString,
        )


class SenderServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Send(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SenderServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Send': grpc.unary_unary_rpc_method_handler(
          servicer.Send,
          request_deserializer=sender__pb2.Message.FromString,
          response_serializer=sender__pb2.Message.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Sender', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
